### ISSUE TITLE
Delete/Change warning when core file is not found

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#12]
See https://github.com/joomla-projects/gsoc18_override_management/pull/9#issuecomment-394153776

We have to decide if we want to show a warning, in the case that there is no core file found. Perhaps we can delete the warning and show the buttons - but show them deactivated if no core file is found.

**Comment by Anu1601CS** [comment]
@astridx PR #11 ,  But we need some suggestions from @laoneo

**Comment by laoneo** [comment]
I would not show a warning, but probably some information text that this file is treated in Joomla as alternative layout.

**Comment by Anu1601CS** [comment]
Ok

**Comment by astridx** [comment]
The warning is now gone. But I want to leave this issue open. Perhaps we have later time to think about @laoneo  suggestion to insert a  information text.

**Comment by Anu1601CS** [comment]
@laoneo Where should we show these information ?
> I would not show a warning, but probably some information text that this file is treated in Joomla as alternative layout.

**Comment by astridx** [comment]
@Anu1601CS @laoneo I'll say my opinion even if I'm not asked :) :

I would like to show a disabled switcher if there is file selected that is no override file.

On hover a tool tip could explain why the switcher is disabled.

For the buttons I made a suggestion here: https://github.com/joomla-projects/gsoc18_override_management/pull/20

But: Disable did not work for the switcher currently: https://github.com/dgrammatiko/40-backend-template/pull/1

**Comment by laoneo** [comment]
I'm fine with that too.
