### ISSUE TITLE
Change Buttons to Switcher

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#13]
![templates customise cassiopeia gsoc administration](https://user-images.githubusercontent.com/9974686/41046581-f5507b72-69aa-11e8-997c-046a46ce385b.png)

Change Buttons to Switcher
https://github.com/joomla/joomla-cms/pull/19232

**Comment by astridx** [comment]
@Anu1601CS  It would be great if you can test
https://github.com/joomla/joomla-cms/pull/20931
and 
https://github.com/joomla/joomla-cms/pull/20929

**Comment by Anu1601CS** [comment]
> @Anu1601CS It would be great if you can test
> joomla/joomla-cms#20931
> and
> joomla/joomla-cms#20929
> 
> Maybe you can give me feedback. Web components you know better than me


@astridx Sorry, I not saw this comment. As I can see dgrammatiko already reviewed your PRs. That's good because I learned these things from him :)

**Comment by astridx** [comment]
Yes. But if it is merges until the end of this project is not sure. 
https://github.com/dgrammatiko/40-backend-template/pull/1
I think we should do our project without the switchers.

**Comment by astridx** [comment]
See: https://github.com/joomla-projects/gsoc18_override_management/pull/35#issuecomment-405905901

**Comment by astridx** [comment]
Close as we have PR: https://github.com/joomla-projects/gsoc18_override_management/pull/35
