### ISSUE TITLE
A few things I noticed in the branch final

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#37]
1. If I disable the installer override plugin and the quickstart icon is enabled the quickstart icon is all the time green. Perhaps we should disable this automatically, if the installer override plugin is disabled?

2. If I mark an override as checked the view is changed. I am redirected to the first tab. 
![templates customise cassiopeia test administration 19](https://user-images.githubusercontent.com/9974686/42737911-3cbaf9c6-887b-11e8-87b4-d1584405b385.png)
Do you think it is possible to stay on the tab “updated files”?

3. In front of the delete button in the view “updated files” there is no space.
![templates customise cassiopeia test administration 17](https://user-images.githubusercontent.com/9974686/42737914-4bf18734-887b-11e8-884e-37b61516d773.png)

4. I still think, that the title modified date is confusing. I think people think, that this is the modified date of the file. But it is the date of the last update. And the created date is the date of the first update in that the file is added to the list. At least this is so in the case of an extension.
![templates customise cassiopeia test administration 18](https://user-images.githubusercontent.com/9974686/42737925-6dd81110-887b-11e8-8db8-150ee9f6ae05.png)

5. The modified date and the created date in case of an joomla update is all the time the same date. It is 2018-06-24 12:39:38

6. I think the button new file, is confusing in our view.

![templates customise test test administration](https://user-images.githubusercontent.com/9974686/42683979-2882189c-868f-11e8-9c3a-062b46c50bae.png)
I see no reason for this buttons in our view.

7. I think we do not need changes in the file `administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-02.sql` because we create this file with charset `utf8mb4_unicode_ci`. I think the `table #__csp` is a new table, too. This table is not changed in `administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-02.sql`, too.

8. We have to decide: What should we do with the new-Api for make it possible to have more than one form on a page? @dgrammatiko  asked to make a pull request to the main repo. Is it possible to separate this files?

**Comment by Anu1601CS** [comment]
> If I disable the installer override plugin and the quickstart icon is enabled the quickstart icon is all the time green. Perhaps we should disable this automatically if the installer override plugin is disabled?

Yes, I am not sure to disable. But we can show another notification text with an error like ( Installer override plugin is disabled please enable to see the result something like that  ).

**Comment by Anu1601CS** [comment]
>  I mark an override as checked the view is changed. I am redirected to the first tab. 

I think this is a bug in the current j4 template. Because I am getting the same issue on main repo as well. Did you check main repo ? its working fine for you?
In previous template all tabs working fine :)

**Comment by Anu1601CS** [comment]
> In front of the delete button in the view “updated files” there is no space.

Its j4 template bug not our. See, other buttons as well.  Same issue.
![screenshot from 2018-07-16 13-07-20](https://user-images.githubusercontent.com/30978328/42747253-4ef409ba-88f9-11e8-928f-1a4ea14b1a1d.png)

**Comment by Anu1601CS** [comment]
> I still think, that the title modified date is confusing. I think people think, that this is the modified date of the file. But it is the date of the last update. And the created date is the date of the first update in that the file is added to the list. At least this is so in the case of an extension.

> The modified date and the created date in case of an joomla update is all the time the same date. It is 2018-06-24 12:39:38 

Yes, for this I am thinking to show only created date no modified date. :)  It's not much important,  I think?

**Comment by Anu1601CS** [comment]
> I think the button new file, is confusing in our view. 

Why? This button is for adding a new file to the template. I think People do not get confused after reading the documentation of this feature.

**Comment by astridx** [comment]
Only for your information: https://github.com/joomla/joomla-cms/issues/21142

**Comment by astridx** [comment]
> @Anu1601CS  Yes, I am not sure to disable. But  we can show another notification text with an error like ( Installer override plugin is disabled please enable to see the result something like that ).

You know my opinion about the many messages, warnings and error pop ups :) 
But I know that's a matter of taste, too. 
Your solution is a solution. But: I would do it differently. I would only display the quickicon if the plugin `installer | overrides` is also active. I would change the text in the quickicon plugin 
from 

`Checks overrides on update and enables notifications when you visit the Control Panel page.`

to something like this:

`Checks if template override files are changed during an update and enables notifications when you visit the Control Panel page. Note: The installer plugin <a href="index.php?option=com_plugins&view=plugin&layout=edit&extension_id=491">overrides</a> has to be enabled, too.`

![plugins quick icon joomla overrides update notification test administration 2](https://user-images.githubusercontent.com/9974686/42760703-90fff816-890b-11e8-8d7a-bfd5c8b57099.png)

**Comment by astridx** [comment]
> Yes, for this I am thinking to show only created date no modified date. :) It's not much important, I think?

I think both dates are good. So you can see that a file has been overwritten a long time ago and does not match the core file. In addition, you can see that it has been changed several times and when it was last modified. I think only that one should write more clearly in the title of the table column what meaning the date has exactly.
For example:
![templates customise cassiopeia test administration 20](https://user-images.githubusercontent.com/9974686/42761444-d6ba35fe-890d-11e8-82fa-70ef2410f0d6.png)

**Comment by astridx** [comment]
> Why? This button is for adding a new file to the template. I think People do not get confused after reading the documentation of this feature.

Because I showed the view a customer/friend who does not use the template manager often. She thought she could add a file to the list of updated files. I think many will think so when using the template manager for the first time. But of course you are right: these people should read the documentary ....

**Comment by dgrammatiko** [comment]
Please change your tabs to our new core ui, check com_contents for a how to (basically just rename the bootstrap.whateverTab to uitab.whatever:
<img width="1277" alt="screenshot 2018-07-16 at 17 41 44" src="https://user-images.githubusercontent.com/3889375/42768345-89ca61a8-891f-11e8-80ad-a25f95f77d76.png">

**Comment by Anu1601CS** [comment]
@dgrammatiko I tried but tabs are not working. All tabs are activated and show content in vertical. Any, idea ? 
![screenshot from 2018-07-16 23-45-49](https://user-images.githubusercontent.com/30978328/42775624-752434ee-8952-11e8-8dc4-8b8a0a21d150.png)

**Comment by Anu1601CS** [comment]
@astridx Now you can see Error if installer plugin is disabled.
![screenshot from 2018-07-17 01-55-56](https://user-images.githubusercontent.com/30978328/42781823-cafc4e26-8964-11e8-866a-a89a02e32dbc.png)

And, if you click on the quick icon then you will redirect to plugin settings to enable.

Also, added information in the plugin.
![screenshot from 2018-07-17 01-56-38](https://user-images.githubusercontent.com/30978328/42781894-ffab7a0c-8964-11e8-8831-15986804acd3.png)

**Comment by dgrammatiko** [comment]
> All tabs are activated and show content in vertical. Any, idea ?

Something is wrong in the supplied code. Refer to article edit view

**Comment by astridx** [comment]
@dgrammatiko Thank you for your reply. 
Here you can find my test code: https://github.com/joomla-projects/gsoc18_override_management/blob/final_tabs2/administrator/components/com_templates/tmpl/template/default.php
All tabs are activated and show content in vertical.  But if I click all tabs, the view is OK. After reloading the page tabs are activated and show content in vertical again. 
It would be great if you have an idea ...

**Comment by dgrammatiko** [comment]
Line 307 is wrong, oy need to change the 'overrides' to something else, this one you used it before and this needs to be unique

**Comment by astridx** [comment]
@dgrammatiko Thank you very much. I corrected that line. But it solved not my problem. Perhaps you have got another idea.

In the line https://github.com/joomla-projects/gsoc18_override_management/blob/4f19607f635e1ff07092fedee4f43d693da9f294/media/system/webcomponents/js/joomla-tab.js#L115
are all tabs marked as acitve, because is `#tab-${tab.hash}` is `#tab-undefined`

**Comment by astridx** [comment]
Close as everything is discussed
