### ISSUE TITLE
Test Joomla Update

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#40]
We have to test Joomla Update after this is fixed: https://github.com/joomla/joomla-cms/issues/21160

**Comment by Anu1601CS** [comment]
@astridx I think, you can test this by just copy paste of older `com_joomlaupdate`  component. Before this PR https://github.com/joomla/joomla-cms/pull/21057

Because we don't know when this issue is going to fix.

**Comment by Anu1601CS** [comment]
@astridx I tested this was working fine for me. Should, I close this?

**Comment by Anu1601CS** [comment]
@astridx I am closing this issue.
