### ISSUE TITLE
question to the feature repair database

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#45]
1. I made a new Installation on the branch joomla-cms 4.0-div. 
2. I changed to this branch 
3. I could discover the plugins.
4. I could not see our view, because our database was not created. I see the message: 
`Table 'joomla_db4.lg5pt_template_overrides' doesn't exist`

5.I thought, that a click on repair database should solve this problem? But I do not know what I have to select or if we have to implement something in our extension for this ….

![extensions database test administration](https://user-images.githubusercontent.com/9974686/42873272-e5452198-8a7e-11e8-9c55-72e98c64cf09.png)

**Comment by Anu1601CS** [comment]
@astridx I did not get this. mean ?

**Comment by astridx** [comment]
It's hard for me to explain what I mean because I've never fully understood the fix database function myself. But I mean that we have to create a file similar to 
/administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-06.sql

If I am right, then the function "fix database" will create our table in case it was not created for any reason.

**Comment by astridx** [comment]
See: https://github.com/joomla-projects/gsoc18_override_management/pull/50

**Comment by astridx** [comment]
Close as PR
