### ISSUE TITLE
Why are we using Codemirror here?

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/gsoc18_override_management#46]
So the question is pretty simple, why?

I would suggest that the monaco editor is a way better fit: https://microsoft.github.io/monaco-editor/

Also since monaco basically derived from the VS-Code codebase I'll go a little bit further and totally replace the codemirror with monaco so we don't end up with 4 editors out of the box.

Please check the diff part, this is what essentially you're after here, right?

**Comment by astridx** [comment]
> Please check the diff part, this is what essentially you're after here, right?

Thank you this hint. 
Are we using the editor monaco already somewhere in joomla 4? I'm afraid that the introduction of a new editor makes the addition to the core difficult. What do you think?
The library we use (for creating the diff) already exists in joomla. the version history uses this.

**Comment by Anu1601CS** [comment]
@dgrammatiko Are you going to replace codemirror to Monaco ?
And, we are not using codemirror for diff. We are using the `jsdiff` that you have suggested in starting of project. Because this library is already in j4 for version history control of article.

**Comment by dgrammatiko** [comment]
>  the jsdiff that you have suggested in starting of project

Actually I suggested that exactly because it was already a dependency for Joomla. What I'm saying is that if we switch to monaco we drop both codemirror and the jsdiff, because monaco can do both tasks.

But **I'm not** the one to do the replacement. I'm just suggesting that we will be better with this editor over codemirror because:
- we have native diff functionality
- we have vs code in joomla which is the defacto editor these days

**Comment by astridx** [comment]
> But I'm not the one to do the replacement. I'm just suggesting that we will be better with this editor over codemirror

@dgrammatiko 
Who decides whether to replace Codemirror with Monaco? I am a bit worried that we will have problems here in the project if we use another editor than the current standard. 
I **personally** would like to use Monaco only if Joomla 4 use it somewhere else and if it was decided that this editor should be used in the future. But I do not see this decision. 
Do you know more?

@Anu1601CS @laoneo What do you think?

**Comment by laoneo** [comment]
For this project it is out of scope to change to Monace. We can consider that for the future and another GsoC project.

**Comment by dgrammatiko** [comment]
I'm gonna do the PR to remove codemirror and replace it with monaco because monaco basically is VS code!
