### ISSUE TITLE
Status labels in com_templates view=templates 

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#51]
![templates templates site test administration 3](https://user-images.githubusercontent.com/9974686/43016368-de3431d4-8c52-11e8-8747-1b74d27c450e.png)

![glip](https://user-images.githubusercontent.com/9974686/43016611-ab80b6da-8c53-11e8-8a3b-7ce2f839cdeb.png)

And I would like it, if a click on a status label redirected to the view (updated files) where the files are listed.

**Comment by Anu1601CS** [comment]
@laoneo Should i text to `conflicts` ?

> And I would like it, if a click on a status label redirected to the view (updated files) where the files are listed.

@astridx I think it's not important. Because user have already an option to go to the list. What do you think ?

**Comment by astridx** [comment]
@Anu1601CS Yes you are right. A redirect in the case of a click on a status label to the view (updated files) is not important. 
I would just like it and if you change the text anyway, it's not a big hassle.

**Comment by astridx** [comment]
@laoneo What should we do with the status labels? Do you have a suggestion?

**Comment by laoneo** [comment]
For me they reflect conglicts with the core file, or not?

**Comment by astridx** [comment]
@laoneo Personally, I do not see "a conflict". It is not the word `conflict` there. It says the word `updated`.
But you like to change that text we can do that. You just have to suggest something :)

**Comment by Anu1601CS** [comment]
See #61
