### ISSUE TITLE
Display of deleted files is broken

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#55]
### Steps to reproduce the issue
1. Make a new installation on the master branch
2. Install an extension. For example: 
[com_agosms-1.0.27.zip](https://github.com/joomla-projects/gsoc18_override_management/files/2223312/com_agosms-1.0.27.zip)

3. Create an override of this extension. 
4. Make an update of the in step 2 installed extension.
5. See that there is an entry in the list of the updated files.
![templates customise cassiopeia test administration](https://user-images.githubusercontent.com/9974686/43134270-d1112786-8f41-11e8-8c8f-a05f74276554.png)

6. Change to the editor tab and delete the override that you have created in step 3

### Expected result
You see in the view of the updated files the entry from step 5 with a hint, that this file is deleted.

### Actual result
You see an empty table
![templates customise cassiopeia test administration 1](https://user-images.githubusercontent.com/9974686/43134399-41035370-8f42-11e8-87e3-a3b7afdd30d4.png)

**Comment by Anu1601CS** [comment]
@astridx We are showing the list for which override is present. 
If the override is not present we don't show that in the list.  And, we only show `core file is deleted ` 
if the core file is deleted in the update.

**Comment by astridx** [comment]
> And, we only show core file is deleted if the core file is deleted while update.

Can you give me a test case in which this happens. I can not find an example at the moment, where 
`if (empty($pk->coreFile))` is `true` here https://github.com/joomla-projects/gsoc18_override_management/blob/36717c403a58cb1a317e321301a644e62b0c604d/plugins/installer/override/override.php#L342

**Comment by Anu1601CS** [comment]
> Can you please give me a test case in which this happens. I can not find an example at the moment, where
if (empty($pk->coreFile)) is true here

In Joomla update, you can find the example of this test case for this condition. 
But, Joomla update has some issue currently.

**Comment by Anu1601CS** [comment]
But, if you really want to test this. Now, you can test manually. 
Like, when you click on `update` or `install`  wait for 1 or 2 seconds while `beforeEventfiles` event trigger. Then, quickly delete some core file of the override. 
Then, you will see your result.

**Comment by astridx** [comment]
> In Joomla update, you can find the example of this test case for this condition.

Is it not possible in extension update?

**Comment by Anu1601CS** [comment]
@astridx I don't know about how to remove file in extension updated. How, to make package to remove any file ? Any idea ?
May be you can add this in your com_agosms package ?

**Comment by astridx** [comment]
See: https://github.com/joomla-projects/gsoc18_override_management/issues/56
