### ISSUE TITLE
Do we want to implement the case that a file is deleted during an extension update?

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#56]
See: https://github.com/joomla-projects/gsoc18_override_management/issues/55#issuecomment-407506389

**Comment by Anu1601CS** [comment]
@astridx, In my opinion, I would say yes. Because may be  it was a bug part of the code. So, in the next update, it was removed.

**Comment by Anu1601CS** [comment]
@laoneo What is your opinion?

**Comment by astridx** [comment]
We could also connect the solution to this issue: https://github.com/joomla-projects/gsoc18_override_management/issues/12

If the core file to `default.php` is deleted, it is OK, that the `override` is in the list of the updated files. The override exist, so this is correct.
![templates customise cassiopeia test administration 2](https://user-images.githubusercontent.com/9974686/43231507-f36b6d9c-906c-11e8-998e-68ab75935740.png)

But if you click on the file name, you will be redirected to the edit tab. And here you see no core file. And you see no buttons. That is confusing.
 
![templates customise cassiopeia test administration 3](https://user-images.githubusercontent.com/9974686/43231563-3a5d8bea-906d-11e8-86cf-90956fb1e33f.png)

But if you would see a warning, like we want to implement in issue https://github.com/joomla-projects/gsoc18_override_management/issues/12 everything would be explained.

**Comment by laoneo** [comment]
I guess both side have pros and cons. I'm fine with whatever you guys feel ok, time will tell.

**Comment by Anu1601CS** [comment]
> But if you click on the file name, you will be redirected to the edit tab. And here you see no core file. And you see no buttons. That is confusing.

@astridx  I also agree with that. Is switcher disable feature is merged?

**Comment by astridx** [comment]
Should I close this issue, because we want to handle it in https://github.com/joomla-projects/gsoc18_override_management/issues/12 ?
