### ISSUE TITLE
label of toolbar buttons

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#58]
I am not happy with the descriptions of the toolbar buttons.

What do you think if we write instead of "Delete" "Delete updated files entry"?

![](https://docs.joomla.org/images/thumb/7/7f/Selection_029.png/800px-Selection_029.png)

**Comment by Anu1601CS** [comment]
@astridx `Delete updated files entry` is very big. Maybe we can use `Delete history` ?

**Comment by astridx** [comment]
See: https://github.com/joomla-projects/gsoc18_override_management/pull/60
