### ISSUE TITLE
Create text for PR together in this issue

### ISSUE THREAD

**Issue by astridx** [joomla-projects/gsoc18_override_management#63]
With the Google Summer of Code 2018 project **_Improve override management_**, we improved the template manager in Joomla! 4. We added a diff view in the override editor. We want to make it possible for every backend user who is allowed to use template manager to see, if a template override file is changed during an update. So users can see possible changes in a diff view and decide, if they want to use this changes in there own override file, too.

**This is especially important when the changes are security-related.**

**Features**
1. Diff View
2. Override - Quick Icon Notification Plugin
3. Installer - Override Plugin
4. Updated - Overrides history list.

### Summary of Changes
Most of the changes done in `com_templates` component, added two new plugin first to check updated files after update and for the quick icon notification.
Added diff view of core and override file so you can see the changes or difference between both the files.
Added new tab to show updated override file list and you can see which files got an update and then you can change your override according to new changes in core.

**What type of problem is going to solve ?**
like if i created the override of any extension then our frontend always use override file insted of core, and then after few days some important bug is fixed or some new changes in functions in an update 
of that extension then its not good for the user because now this application creates issue.

So, by using this user can checks new updated file changes and feel good :) 

### Testing Instructions
For this you need an extension which have an update with new chnages in extension files.
So, 
1. Go to template manager.
2. Create an override of that extension before update.
3. See the diff view of that file by using toggle button in top right corner. **Expexted :**  No difference.
4. Now update your extension. **Expexted :** If your created override file got any update in core you can see notification message number of files updated.
5. Go to template manager check new tab you can see which files is update.
6. Click on name of file you will get redirect to edit view of that file. 
7. Now you can see the changes in diff view.
8. Adjust your override file if you want and then you can delete that file list history or mark as checked.

### Documentation Changes Required
**Repo** https://github.com/joomla-projects/gsoc18_override_management/
**Documentation** https://docs.joomla.org/J4.x:Improved_Override_Management

**Comment by astridx** [comment]
I'm not sure if we should enclose an example extension here? 

A Joomla update does not work yet, right? Should we wait for this?

**Comment by astridx** [comment]
There is a special event for testing prs on the 9th of September (https://www.joomla.de/news/events/501-pizzalieferanten-lieben-joomla). Perhaps we should try to create the pr before this date.
What do you mean, can we reach this?

**Comment by Anu1601CS** [comment]
> What do you mean, can we reach this?

Yes :)

**Comment by Anu1601CS** [comment]
@astridx Added few things

**Comment by Anu1601CS** [comment]
see https://github.com/joomla/joomla-cms/pull/21851
