### ISSUE TITLE
Implement the diff view in template manager

### ISSUE THREAD

**Issue by Anu1601CS** [joomla-projects/gsoc18_override_management#7]

**Comment by astridx** [comment]
The warnings confused me a little today.

Perhaps we do not need this warnung, when a core file is not found. We can show the normal view. Nobody expects a diff view if we do not show a button to show (toggle) this view.
![templates customise cassiopeia test administration 1](https://user-images.githubusercontent.com/9974686/40813416-07ac0c56-653b-11e8-92d1-1fe637341354.png)

The same applies to areas outside the html folder. We do not have to tell anyone who opens the css folder that the diff view is only possible in the html folder. Nobody expects the diff view in the css folder.
![templates customise cassiopeia test administration 2](https://user-images.githubusercontent.com/9974686/40813417-07c83e6c-653b-11e8-9939-e37861253cc2.png)

The next picture was very confusing for me.
I looked at a css file. Then I opened the tab "Create Overrides". Then I'm back in the tab "Editor". Then I got these three warnings displayed.
![templates customise cassiopeia test administration 3](https://user-images.githubusercontent.com/9974686/40813418-07e5f934-653b-11e8-8a07-edddb6111549.png)

So what do you think? Should we show fewer warnings?

**Comment by laoneo** [comment]
Agree on the first two screenshots. This messages are not needed.

**Comment by Anu1601CS** [comment]
@astridx @laoneo Yes, both of you are right. If do not show diff view button then nobody expects this.  So, I do PR to remove this.

**Comment by Anu1601CS** [comment]
Done!
