### ISSUE TITLE
Hard-coded extension ID in JS

### ISSUE THREAD

**Issue by richard67** [joomla-projects/gsoc18_override_management#83]
This issue is just a reminder to clarify and if possible fix the hard-coded extension ID here:
[File build/media_src/plg_quickicon_overridecheck/js/overridecheck.es6.js, line 51](https://github.com/joomla-projects/gsoc18_override_management/blob/master/build/media_src/plg_quickicon_overridecheck/js/overridecheck.es6.js#L51)
It needs to be checked if such a use of hard-coded extension ID is normal because used in other JS, too, or if not, how it can be fixed.

**Comment by Anu1601CS** [comment]
See this https://github.com/joomla/joomla-cms/pull/21851#issuecomment-417942717
